### ISSUE TITLE
TypeError when using the enchant macro on Armor

### ISSUE THREAD

**Issue by JasonSK22** [brunocalado/savage-pathfinder-enhanced#8]
Hi Brunocalado,

I am running into this error when using the enchantment macro on Armor (does not happen on weapons)

```
Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'price')
[No packages detected]
    at forgeMasterwork (eval at #executeScript (foundry.js:20082:16), <anonymous>:522:35)
    at enchantItem (eval at #executeScript (foundry.js:20082:16), <anonymous>:464:26)
    at Dialog.callback (eval at #executeScript (foundry.js:20082:16), <anonymous>:452:11)
    at Dialog.submit (foundry.js:68861:46)
    at Dialog._onClickButton (foundry.js:68789:10)
    at HTMLButtonElement.dispatch (jquery.min.js:2:40035)
    at v.handle (jquery.min.js:2:38006)


    
    Any idea what is happen here?
    
    Thanks
    
    Jason

**Comment by brunocalado** [comment]
Fixed. Update. The macro is fixed in the compendium
